// src/components/vue/CardItem.vue
<script setup lang="ts">
import { computed } from 'vue';
import { blankCard as defaultImage } from '../../assets/images';
import type { Card } from '../../utils/app.mock';

const props = defineProps<{
	item: Card;
}>();
const imagePath = computed(() => (props.item.isOpen ? props.item.pic : defaultImage));
defineEmits<{
	'card-click': [number];
}>();
</script>

<template>
	<div
		:id="String(item.id)"
		class="m-3 cursor-pointer rounded-lg bg-white p-2 shadow-md transition-shadow duration-300 ease-in-out hover:shadow-xl"
		@click="$emit('card-click', item.id)">
		<img height="150" width="120" :src="imagePath" alt="Image" />
	</div>
</template>

<style scoped>
div {
	border: 2px solid green;
}
</style>

// src/components/solid/CardItem.solid.tsx
import { createMemo } from 'solid-js';
import { blankCard as defaultImage } from '../../assets/images';
import type { Card } from '../../utils/app.mock';

type Props = { item: Card; onCardClick: (id: number) => void };
export default function (props: Props) {
	const imagePath = createMemo(() => (props.item.isOpen ? props.item.pic : defaultImage));

	return (
		<div
			id={String(props.item.id)}
			style="{border: 2px solid green;}"
			class="m-3 cursor-pointer rounded-lg bg-white p-2 shadow-md transition-shadow duration-300 ease-in-out hover:shadow-xl"
			onClick={() => props.onCardClick(props.item.id)}>
			<img height="150" width="120" src={imagePath()} alt="Image" />
		</div>
	);
}
